apiVersion: "nextbreakpoint.com/v1"
kind: FlinkCluster
metadata:
  name: test
spec:
  pullSecrets: regcred
  pullPolicy: IfNotPresent
  flinkImage: nextbreakpoint/flink:1.7.2-1
  sidecarServiceAccount: flink-sidecar
  sidecarImage: 192.168.1.11:30000/nextbreakpoint/flink-workshop-jobs:2
  sidecarJarPath: /com.nextbreakpoint.flinkworkshop-1.0.0.jar
  sidecarClassName: com.nextbreakpoint.flink.jobs.TestJob
  sidecarParallelism: 1
  sidecarArguments:
    - --BUCKET_BASE_PATH
    - file:///var/tmp
  jobmanagerEnvironmentVariables:
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
  taskmanagerEnvironmentVariables:
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
